= MongoDB

== 1.0 Delete a large amount of data and free up space in MongoDB.

There are two ways to reclaim disk space in Percona Server for MongoDB (PSMDB): run compact on nodes or resync the node.

 CAUTION: This procedure is for MongoDB from version 4.4+

Script for deleting data in batchs:

[source, mongodb]
----
use dbname
----

[source, java]
----
var coll   = db.tickets;                // <-- change me
var cutoff = ISODate("2023-09-28T00:00:00Z");  // delete dt older than this
var batch  = 10000;                            // tune (e.g., 1000–20000)
// TIP: speed up the scan (run once, optional)
// coll.createIndex({ dt: 1 });
// LOOP
while (true) {
  // Grab a batch of _ids to delete (projection avoids loading full docs)
  var ids = coll.find(
      { dt: { $lt: cutoff } },
      { _id: 1 }
    )
    .limit(batch)
    .toArray()
    .map(function (d) { return d._id; });
  if (ids.length === 0) {
    print("Done.");
    break;
  }
  // Delete exactly that batch
  var res = coll.deleteMany({ _id: { $in: ids } });
  print("Deleted: " + res.deletedCount);
  // If we got fewer than a full batch, we're finished
  if (ids.length < batch) {
    print("Last partial batch. Done.");
    break;
  }
}
----

We can check sizes of data:

``db.stats()`` 

Check size of space that can be reclaimed:

``db.collectionname.stats().wiredTiger["block-manager"]["file bytes available for reuse"]``



[IMPORTANT]
====
* The user should have the required privilege to run the compact command.

* Check if you have enough replication oplog window.

* In a shard cluster, a compact command need to be run on each node of every shard. Compact cannot be run against the mongos. 
====


CAUTION: In MongoDB version 4.4 or newer, compact will only block metadata operations such as dropping a collection, dropping an index, or creating a new index.



**In a replica set, the compact command must be run on every node.Always run compact on secondary or hidden nodes, or on nodes with a low priority. Process the primary node last, after you have stepped it down.**

[source,mongodb]
----
db.runCommand({ compact: 'collectionname', force: true });
----


CAUTION: Sometimes, when a large collection is compacted, the compact command immediately returns OK, but in reality, the physical space of the collection remains unchanged. This is because WiredTiger deems that the collection does not need to be compacted. To overcome this, you need to run the compact command again until it releases the space.

TIP: Compact oplog.rs to reclaim disk space.
Reducing the size of the oplog does not automatically reclaim the disk space allocated to the original oplog size. You must run compact against the oplog.rs collection in the local database to reclaim disk space. There are no benefits to running compact on the oplog.rs collection after increasing the oplog size.
A replica set member cannot replicate oplog entries when a compact operation is ongoing on oplog.rs because it prevents oplog synchronization. You must schedule compact operations on the oplog during a maintenance window. Oplog replication cannot occur during that time window.

== 2.0 Rename hosts in replica set




= PXC

== 1.0 Changing synchronous node to asynchronous

On target node we type:

[source, mysql]
----
SET GLOBAL wsrep_cluster_address='dummy://';

set session wsrep_on=OFF ;
----

CAUTION: Change server ID if same on master


[source, mysql]
----
STOP REPLICA;
CHANGE MASTER TO
  MASTER_HOST = 'xxxxx',
  MASTER_PORT = xxxx,
  MASTER_USER = 'xxxxx',
  MASTER_PASSWORD = 'xxxxxxxxxxx',
  MASTER_AUTO_POSITION = 1;

CHANGE MASTER TO
  MASTER_SSL=1,
  MASTER_SSL_VERIFY_SERVER_CERT=0,
  MASTER_SSL_CA = '/etc/ssl/mysql/ca-cert.pem',
  MASTER_SSL_CERT = '/etc/ssl/mysql/client-cert.pem',
  MASTER_SSL_KEY = '/etc/ssl/mysql/client-key.pem';

START REPLICA;

SHOW REPLICA STATUS\G
----

Shutdown

Restart with conf  ``wsrep: "false"``